/* eslint-disable n8n-nodes-base/node-param-operation-option-action-miscased */
/* eslint-disable n8n-nodes-base/node-param-options-type-unsorted-items */
import type { INodeProperties, INodePropertyOptions } from 'n8n-workflow';

export const AVAILABLE_ACTION = {
	checkConnectionStatus: 'checkConnectionStatus',
	commentOnPost: 'commentOnPost',
	createPost: 'createPost',
	fetchCompany: 'fetchCompany',
	fetchPerson: 'fetchPerson',
	fetchPost: 'fetchPost',
	fetchJob: 'fetchJob',
	reactToPost: 'reactToPost',
	removeConnection: 'removeConnection',
	retrieveConnections: 'retrieveConnections',
	retrieveConnectionRequests: 'retrieveConnectionRequests',
	retrievePendingRequests: 'retrievePendingRequests',
	retrievePerformance: 'retrievePerformance',
	retrieveSSI: 'retrieveSSI',
	searchCompanies: 'searchCompanies',
	searchPeople: 'searchPeople',
	searchJobs: 'searchJobs',
	sendConnectionRequest: 'sendConnectionRequest',
	acceptConnectionRequest: 'acceptConnectionRequest',
	ignoreConnectionRequest: 'ignoreConnectionRequest',
	sendMessage: 'sendMessage',
	syncConversation: 'syncConversation',
	syncInbox: 'syncInbox',
	syncNetwork: 'syncNetwork',
	manageConversation: 'manageConversation',
	withdrawConnectionRequest: 'withdrawConnectionRequest',
	nvFetchCompany: 'nvFetchCompany',
	nvFetchPerson: 'nvFetchPerson',
	nvSearchCompanies: 'nvSearchCompanies',
	nvSearchPeople: 'nvSearchPeople',
	nvSendMessage: 'nvSendMessage',
	nvSyncConversation: 'nvSyncConversation',
	nvSyncInbox: 'nvSyncInbox',
	nvManageConversation: 'nvManageConversation',
	customWorkflow: 'customWorkflow',
	getWorkflowResult: 'getWorkflowResult',
	cancelWorkflow: 'cancelWorkflow',
	pollConversations: 'pollConversations',
	pollInbox: 'pollInbox',
	pollNetwork: 'pollNetwork',
	actionsUsageStatistics: 'actionsUsageStatistics',
	adminGetSubscriptionStatus: 'adminGetSubscriptionStatus',
	adminGetSeats: 'adminGetSeats',
	adminSetSeats: 'adminSetSeats',
	adminGetAccounts: 'adminGetAccounts',
	adminReparseAccountInfo: 'adminReparseAccountInfo',
	adminCreateReconnectionSession: 'adminCreateReconnectionSession',
	adminConnectAccount: 'adminConnectAccount',
	adminGetConnectionSession: 'adminGetConnectionSession',
	adminCancelConnectionSession: 'adminCancelConnectionSession',
	adminDisconnectAccount: 'adminDisconnectAccount',
	adminRegenerateToken: 'adminRegenerateToken',
	adminGetLimitsDefaults: 'adminGetLimitsDefaults',
	adminGetLimits: 'adminGetLimits',
	adminGetLimitsUsage: 'adminGetLimitsUsage',
	adminSetLimits: 'adminSetLimits',
	adminDeleteLimits: 'adminDeleteLimits',
	adminResetLimits: 'adminResetLimits',
} as const;
export type TAvailableAction = (typeof AVAILABLE_ACTION)[keyof typeof AVAILABLE_ACTION];

export const availableStandardOperations: INodeProperties = {
	displayName: 'Operation',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	default: AVAILABLE_ACTION.searchCompanies.toString(),
	displayOptions: {
		show: {
			resource: ['standard'],
		},
	},
	options: [
		{
			name: 'Check Connection Status',
			value: AVAILABLE_ACTION.checkConnectionStatus,
			description: 'Check the connection status between your account and another person',
			action: 'Check connection status',
		},
		{
			name: 'Comment on Post',
			value: AVAILABLE_ACTION.commentOnPost,
			description: 'Leave a comment on a LinkedIn post',
			action: 'Comment on post',
		},
		{
			name: 'Create Post',
			value: AVAILABLE_ACTION.createPost,
			description: 'Create a new LinkedIn post',
			action: 'Create post',
		},
		{
			name: 'Fetch Company',
			value: AVAILABLE_ACTION.fetchCompany,
			description: 'Fetch detailed information about a LinkedIn company',
			action: 'Fetch company',
		},
		{
			name: 'Fetch Person',
			value: AVAILABLE_ACTION.fetchPerson,
			description: 'Fetch detailed information about a LinkedIn person',
			action: 'Fetch person',
		},
		{
			name: 'Fetch Post',
			value: AVAILABLE_ACTION.fetchPost,
			description: 'Retrieve detailed information about a LinkedIn post',
			action: 'Fetch post',
		},
		{
			name: 'Fetch Job',
			value: AVAILABLE_ACTION.fetchJob,
			description: 'Fetch detailed information about a LinkedIn job',
			action: 'Fetch job',
		},
		{
			name: 'React to Post',
			value: AVAILABLE_ACTION.reactToPost,
			description:
				'React to a LinkedIn post with like, celebrate, support, love, insightful, or funny',
			action: 'React to post',
		},
		{
			name: 'Remove Connection',
			value: AVAILABLE_ACTION.removeConnection,
			description: 'Remove a person from your connections',
			action: 'Remove connection',
		},
		{
			name: 'Retrieve Connections',
			value: AVAILABLE_ACTION.retrieveConnections,
			description: 'Retrieve your connections with optional filtering',
			action: 'Retrieve connections',
		},
		{
			name: 'Retrieve Connection Requests',
			value: AVAILABLE_ACTION.retrieveConnectionRequests,
			description: 'Retrieve incoming connection requests received by your account',
			action: 'Retrieve connection requests',
		},
		{
			name: 'Retrieve Pending Requests',
			value: AVAILABLE_ACTION.retrievePendingRequests,
			description: 'Retrieve pending connection requests sent from your account',
			action: 'Retrieve pending requests',
		},
		{
			name: 'Retrieve Performance',
			value: AVAILABLE_ACTION.retrievePerformance,
			description: 'Retrieve performance analytics from your LinkedIn dashboard',
			action: 'Retrieve performance',
		},
		{
			name: 'Retrieve SSI',
			value: AVAILABLE_ACTION.retrieveSSI,
			description: 'Retrieve your current Social Selling Index (SSI) score',
			action: 'Retrieve SSI',
		},
		{
			name: 'Search Companies',
			value: AVAILABLE_ACTION.searchCompanies,
			description: 'Search for companies on LinkedIn',
			action: 'Search companies',
		},
		{
			name: 'Search People',
			value: AVAILABLE_ACTION.searchPeople,
			description: 'Search for people on LinkedIn',
			action: 'Search people',
		},
		{
			name: 'Search Jobs',
			value: AVAILABLE_ACTION.searchJobs,
			description: 'Search for jobs on LinkedIn',
			action: 'Search jobs',
		},
		{
			name: 'Send Connection Request',
			value: AVAILABLE_ACTION.sendConnectionRequest,
			description: 'Send a connection request to a person',
			action: 'Send connection request',
		},
		{
			name: 'Accept Connection Request',
			value: AVAILABLE_ACTION.acceptConnectionRequest,
			description: 'Accept an incoming connection request from a person',
			action: 'Accept connection request',
		},
		{
			name: 'Ignore Connection Request',
			value: AVAILABLE_ACTION.ignoreConnectionRequest,
			description: 'Ignore an incoming connection request from a person',
			action: 'Ignore connection request',
		},
		{
			name: 'Send Message',
			value: AVAILABLE_ACTION.sendMessage,
			description: 'Send a message to a LinkedIn person',
			action: 'Send message',
		},
		{
			name: 'Sync Conversation',
			value: AVAILABLE_ACTION.syncConversation,
			description: 'Sync a conversation so you can start polling it for new messages',
			action: 'Sync conversation',
		},
		{
			name: 'Sync Inbox',
			value: AVAILABLE_ACTION.syncInbox,
			description: 'Enable whole-inbox monitoring so every incoming conversation can be polled',
			action: 'Sync inbox',
		},
		{
			name: 'Sync Network',
			value: AVAILABLE_ACTION.syncNetwork,
			description: 'Enable background network monitoring so connection changes can be polled',
			action: 'Sync network',
		},
		{
			name: 'Manage Conversation',
			value: AVAILABLE_ACTION.manageConversation,
			description: 'Archive, star, or mute a conversation thread by thread ID',
			action: 'Manage conversation',
		},
		{
			name: 'Withdraw Connection Request',
			value: AVAILABLE_ACTION.withdrawConnectionRequest,
			description: 'Withdraw a connection request sent to a person',
			action: 'Withdraw connection request',
		},
	],
};

export const availableSalesNavigatorOperations: INodeProperties = {
	displayName: 'Operations',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	default: AVAILABLE_ACTION.nvSearchCompanies.toString(),
	displayOptions: {
		show: {
			resource: ['salesNavigator'],
		},
	},
	options: [
		{
			name: 'Fetch Company in Sales Navigator',
			value: AVAILABLE_ACTION.nvFetchCompany,
			description: 'Fetch detailed information about a company in Sales Navigator',
			action: 'Fetch company in Sales Navigator',
		},
		{
			name: 'Fetch Person in Sales Navigator',
			value: AVAILABLE_ACTION.nvFetchPerson,
			description: 'Fetch detailed information about a person in Sales Navigator',
			action: 'Fetch person in Sales Navigator',
		},
		{
			name: 'Search Companies in Sales Navigator',
			value: AVAILABLE_ACTION.nvSearchCompanies,
			description: 'Search for companies in Sales Navigator',
			action: 'Search companies in Sales Navigator',
		},
		{
			name: 'Search People in Sales Navigator',
			value: AVAILABLE_ACTION.nvSearchPeople,
			description: 'Search for people in Sales Navigator',
			action: 'Search people in Sales Navigator',
		},
		{
			name: 'Send Message in Sales Navigator',
			value: AVAILABLE_ACTION.nvSendMessage,
			description: 'Send a message to a person in Sales Navigator',
			action: 'Send message in Sales Navigator',
		},
		{
			name: 'Sync Conversation in Sales Navigator',
			value: AVAILABLE_ACTION.nvSyncConversation,
			description: 'Sync a conversation in Sales Navigator so you can start polling it',
			action: 'Sync conversation in Sales Navigator',
		},
		{
			name: 'Sync Inbox in Sales Navigator',
			value: AVAILABLE_ACTION.nvSyncInbox,
			description:
				'Enable whole-inbox monitoring in Sales Navigator so every incoming conversation can be polled',
			action: 'Sync inbox in Sales Navigator',
		},
		{
			name: 'Manage Conversation in Sales Navigator',
			value: AVAILABLE_ACTION.nvManageConversation,
			description: 'Archive or unarchive a conversation thread by thread ID via Sales Navigator',
			action: 'Manage conversation in Sales Navigator',
		},
	],
};

export const customWorkflowOption: INodePropertyOptions = {
	name: 'Custom Workflow',
	value: AVAILABLE_ACTION.customWorkflow,
	description: 'Execute a custom multi-step workflow using raw workflow definition',
	action: 'Execute custom workflow',
};

export const availableOtherOperations: INodeProperties = {
	displayName: 'Operations',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	default: AVAILABLE_ACTION.customWorkflow.toString(),
	displayOptions: {
		show: {
			resource: ['other'],
		},
	},
	options: [
		{
			name: 'Custom Workflow',
			value: AVAILABLE_ACTION.customWorkflow,
			description: 'Execute a custom multi-step workflow using raw workflow definition',
			action: 'Execute custom workflow',
		},
		{
			name: 'Get Workflow Result',
			value: AVAILABLE_ACTION.getWorkflowResult,
			description: 'Get the result of workflow execution',
			action: 'Get workflow result',
		},
		{
			name: 'Cancel Workflow',
			value: AVAILABLE_ACTION.cancelWorkflow,
			description: 'Cancel a running workflow execution',
			action: 'Cancel workflow',
		},
		{
			name: 'Poll Conversations',
			value: AVAILABLE_ACTION.pollConversations,
			description: 'Poll multiple conversations for new messages',
			action: 'Poll conversations',
		},
		{
			name: 'Poll Inbox',
			value: AVAILABLE_ACTION.pollInbox,
			description: 'Poll the monitored inbox for new messages across all conversations',
			action: 'Poll inbox',
		},
		{
			name: 'Poll Network',
			value: AVAILABLE_ACTION.pollNetwork,
			description: 'Poll the monitored network for new connection events',
			action: 'Poll network',
		},
		{
			name: 'Actions Usage Statistics',
			value: AVAILABLE_ACTION.actionsUsageStatistics,
			description: 'Get actions usage statistics for a date range',
			action: 'Get actions statistics',
		},
	],
};

export const availableAdminOperations: INodeProperties = {
	displayName: 'Operations',
	name: 'operation',
	type: 'options',
	noDataExpression: true,
	default: AVAILABLE_ACTION.adminGetAccounts.toString(),
	displayOptions: {
		show: {
			resource: ['admin'],
		},
	},
	options: [
		{
			name: 'Get Subscription Status',
			value: AVAILABLE_ACTION.adminGetSubscriptionStatus,
			description: 'Get current subscription status and trial eligibility',
			action: 'Get subscription status',
		},
		{
			name: 'Get Seats',
			value: AVAILABLE_ACTION.adminGetSeats,
			description: 'Get active subscription seats',
			action: 'Get seats',
		},
		{
			name: 'Set Seats',
			value: AVAILABLE_ACTION.adminSetSeats,
			description: 'Set number of subscription seats',
			action: 'Set seats',
		},
		{
			name: 'Get Accounts',
			value: AVAILABLE_ACTION.adminGetAccounts,
			description: 'Get all connected LinkedIn accounts, pending sessions, and reconnection links',
			action: 'Get accounts',
		},
		{
			name: 'Reparse Account Info',
			value: AVAILABLE_ACTION.adminReparseAccountInfo,
			description: 'Refresh stored profile URL, avatar, headline, and name for a connected account',
			action: 'Reparse account info',
		},
		{
			name: 'Reconnect Account',
			value: AVAILABLE_ACTION.adminCreateReconnectionSession,
			description: 'Create reconnection session for an account that requires reconnection',
			action: 'Reconnect account',
		},
		{
			name: 'Connect Account',
			value: AVAILABLE_ACTION.adminConnectAccount,
			description: 'Create connection session for a new LinkedIn account',
			action: 'Connect account',
		},
		{
			name: 'Get Connection Session',
			value: AVAILABLE_ACTION.adminGetConnectionSession,
			description: 'Get connection or reconnection session status',
			action: 'Get connection session',
		},
		{
			name: 'Cancel Connection Session',
			value: AVAILABLE_ACTION.adminCancelConnectionSession,
			description: 'Cancel a pending connection or reconnection session',
			action: 'Cancel connection session',
		},
		{
			name: 'Disconnect Account',
			value: AVAILABLE_ACTION.adminDisconnectAccount,
			description: 'Disconnect a LinkedIn account (irreversible)',
			action: 'Disconnect account',
		},
		{
			name: 'Regenerate Token',
			value: AVAILABLE_ACTION.adminRegenerateToken,
			description: 'Regenerate identification token for an account',
			action: 'Regenerate token',
		},
		{
			name: 'Get Limits Defaults',
			value: AVAILABLE_ACTION.adminGetLimitsDefaults,
			description: 'Get system default rate limits',
			action: 'Get limits defaults',
		},
		{
			name: 'Get Limits',
			value: AVAILABLE_ACTION.adminGetLimits,
			description: 'Get configured rate limits for an account',
			action: 'Get limits',
		},
		{
			name: 'Get Limits Usage',
			value: AVAILABLE_ACTION.adminGetLimitsUsage,
			description: 'Get current usage against configured limits',
			action: 'Get limits usage',
		},
		{
			name: 'Set Limits',
			value: AVAILABLE_ACTION.adminSetLimits,
			description: 'Set rate limits for an account',
			action: 'Set limits',
		},
		{
			name: 'Delete Limits',
			value: AVAILABLE_ACTION.adminDeleteLimits,
			description: 'Delete specific account rate limits',
			action: 'Delete limits',
		},
		{
			name: 'Reset Limits',
			value: AVAILABLE_ACTION.adminResetLimits,
			description: 'Reset all limits to system defaults',
			action: 'Reset limits',
		},
	],
};
